# Extract audio
-x

# Formats the output files
-o "/%(artists.0)s/%(title)s.%(ext)s"

# Format to mp3
--audio-format mp3

# Best audio quality
--audio-quality 0

# Show progress while downloading
--progress

# Archive text file skips songs that are already downloaded
--download-archive downloadarchive.txt

# Don't stop download process if a song is in the archive
--no-break-on-existing

# Adjust metadata to add only the first artist
--parse-metadata %(artists.0)s:%(meta_artist)s

# Embeds the metadata from downloaded to the mp3
--embed-metadata

# Embed the thumbnail as album art
--embed-thumbnail

# Set the thumbnail to square ratio
--ppa "EmbedThumbnail+ffmpeg_o:-c:v mjpeg -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\""
